### ISSUE TITLE
This project is currently not under active development

### ISSUE THREAD

**Issue by bzvestey** [SAML-Toolkits/ruby-saml#640]
Hello everyone, we here at OneLogin wanted to let you know that this project is currently not under active development. We apologize for recent silence and continued wait, but we intend to resume maintenance in the future.

Note that I am unable to make any more changes to this repository, and I don't have someone I can forward you to at this time.

**Comment by chipach** [comment]
For others who stumbled here, see https://github.com/onelogin/java-saml/issues/388 for @pitbulk offering to take over maintenance of the various OneLogin open source SAML client repos.

**Comment by eriktalvi** [comment]
Development Update. OneLogin is releasing these projects to a new organization with @pitbulk. This migration is actively happening and the priority is to make the transition as seamless as possible for end users of these repo/packages.

We expect that there are several questions that you all have and we are working with @pitbulk to answer those in our next update. Below are some answers we have for you now.

What is being changed?
The repos/packages will no longer be officially supported and hosted by OneLogin. This means that they will not be in the OneLogin Github org but in a new org, SAML Tools. References to the repos being provided and supported by OneLogin Inc will be removed.

Which projects are being moved?
All SAML repos will be moved. This includes: java-saml, python3-saml, wordpress-saml, moodle-saml, joomla-saml, drupal-saml, and dotnet-saml

When will this transfer happen?
We expect this to be completed by the end of the year, Dec 31 2022.

Why is this transfer happening?
OneLogin is releasing control of these open source repos so that these repos can maintained by community instead.

When will the next update be?
To keep you all informed of status, we will give monthly updates of how the transfer is proceeding.

**Comment by StoneCypher** [comment]
@pitbulk - congratulations, Sixto

**Comment by eriktalvi** [comment]
Development Update. Although it may not seem like it, the last month had a lot of progress and the primary SAML Toolkit repos and packages have been transferred from OneLogin to this new SAML Toolkit Org.

@pitbulk now has all the access needed to maintain these toolkits and will be providing his own update.

There has been a lot of pent up demand for support on these repos and now that this transfer is finished you should expect to see a lot more progress on that!

There are still four repos (wordpress-saml, moodle-saml, joomla-saml, drupal-saml) left to transfer and these will be finished in the upcoming weeks.

Cheers!

**Comment by pitbulk** [comment]
I gonna maintain the project, so this warning is not required anymore ;)
